// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yehxlphlddyzrnewfelr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InllaHhscGhsZGR5enJuZXdmZWxyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2NjYzMTEsImV4cCI6MjA2MDI0MjMxMX0.S5xeCv8JERDGFKKwvNBYVcrmjBb4_Fyg_lEBBM2s5Ws";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);