
export const foodOptions = [
  "Aceite de oliva",
  "Carne roja",
  "Carne blanca",
  "Pescado blanco",
  "Pescado azul",
  "Procesados veganos",
  "Pan",
  "Mermelada",
  "Bebida vegetal",
  "Cereales",
  "Lácteos",
  "Aguacate",
  "Conservas de pescado",
  "Huevo",
  "Miel",
  "Legumbre",
  "Frutos secos",
  "Mantequilla",
  "Boniato",
  "Encuertidos",
  "Patata",
  "Fiambres"
];
